"""
TaxAdjustment SQLAlchemy model.

Adjustments generated by tax rules.
"""
import uuid
from sqlalchemy import Column, String, Text, Numeric, ForeignKey, DateTime, func, Index
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from app.db.base import Base


class TaxAdjustment(Base):
    """
    Tax adjustments generated by applying rules to facts.
    Examples: book-tax differences, permanent adjustments, timing differences.
    """
    __tablename__ = "tax_adjustments"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Run reference
    tax_run_id = Column(UUID(as_uuid=True), ForeignKey("tax_runs.id", ondelete="CASCADE"), nullable=False, index=True)

    # Company
    company_id = Column(UUID(as_uuid=True), ForeignKey("companies.id"), nullable=False, index=True)

    # Tax type
    tax_type = Column(String, nullable=False)  # "PASS_THROUGH_INCOME", "AMT", "STATE_APPORTIONMENT"

    # Adjustment details
    adjustment_type = Column(String, nullable=False)  # "permanent", "timing", "reclass", "limit"
    amount = Column(Numeric(15, 2), nullable=False)

    # Rule reference
    rule_id = Column(String, nullable=False)  # "meal_entertainment_50_limit", "depreciation_macrs"
    reason = Column(Text, nullable=False)  # Human-readable explanation

    # Source facts
    source_fact_ids = Column(JSONB, nullable=False, default=list)  # ["fact_uuid_1", "fact_uuid_2"]

    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    tax_run = relationship("TaxRun", back_populates="tax_adjustments")
    company = relationship("Company")

    def __repr__(self):
        return f"<TaxAdjustment(tax_type='{self.tax_type}', amount={self.amount}, rule='{self.rule_id}')>"
