FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./

# Skip npm install in Dockerfile.dev as we will mount node_modules from host
# RUN npm install

COPY . .

CMD ["npm", "run", "dev", "--", "--host"]
