
import os
import re

if os.path.exists("alembic/versions"):
    VERSIONS_DIR = "alembic/versions"
else:
    VERSIONS_DIR = "backend/alembic/versions"

def fix_000():
    filepath = os.path.join(VERSIONS_DIR, "000_baseline.py")
    with open(filepath, "r") as f:
        content = f.read()

    # Extract revision ID
    match = re.search(r"revision = '([a-f0-9]+)'", content)
    if not match:
        raise ValueError("Could not find revision ID in 000_baseline.py")
    revision_id = match.group(1)

    # Add vector extension and import
    if "import pgvector" not in content:
        content = content.replace("import sqlalchemy as sa", "import sqlalchemy as sa\nimport pgvector")

    if "op.execute('CREATE EXTENSION" not in content:
        content = content.replace("def upgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###", 
                                  "def upgrade() -> None:\n    op.execute('CREATE EXTENSION IF NOT EXISTS vector')\n    # ### commands auto generated by Alembic - please adjust! ###")

    # Tables to remove from 000
    # We keep group_companies because invitations depends on it.
    # We remove tax tables because 025 creates them (and nothing depends on them in 000? tax_facts?)
    # Tax tables are isolated.
    tables_to_remove = [
        "entity_tax_profiles",
        "tax_rulesets",
        "tax_runs",
        "tax_facts",
        "tax_adjustments",
        "tax_positions"
    ]

    lines = content.splitlines()
    new_lines = []
    skip = False
    
    for line in lines:
        if skip:
            if line.strip() == ")" or line.strip() == ")":
                 skip = False
                 continue
            continue

        # Check for create table 
        match_table = re.search(r"op\.create_table\('(\w+)'", line)
        if match_table:
            table_name = match_table.group(1)
            if table_name in tables_to_remove:
                skip = True
                continue
        
        # Check for indexes for removed tables
        is_index_removal = False
        for table in tables_to_remove:
            if f"'{table}'" in line and "op.create_index" in line:
                is_index_removal = True
                break
        
        if is_index_removal:
            continue
            
        # Also drop_table and drop_index in downgrade
        match_drop = re.search(r"op\.drop_table\('(\w+)'", line)
        if match_drop:
            if match_drop.group(1) in tables_to_remove:
                continue
                
        is_drop_index = False
        for table in tables_to_remove:
            if f"table_name='{table}'" in line and "op.drop_index" in line:
                is_drop_index = True
                break
        if is_drop_index:
            continue

        new_lines.append(line)

    with open(filepath, "w") as f:
        f.write("\n".join(new_lines))
    print(f"Fixed 000_baseline.py (ID: {revision_id})")
    return revision_id

def fix_001(baseline_id):
    # Set parent to baseline
    filepath = os.path.join(VERSIONS_DIR, "001_create_group_companies_tables.py")
    with open(filepath, "r") as f:
        content = f.read()
    
    # Replace any existing down_revision
    content = re.sub(r"down_revision = .*", f"down_revision = '{baseline_id}'", content)
    
    with open(filepath, "w") as f:
        f.write(content)
    print("Fixed 001 parent")

def blank_out_intermediate():
    # 001 to 024 (Inclusive now!)
    # We iterate files, check prefix.
    files = sorted(os.listdir(VERSIONS_DIR))
    for filename in files:
        if filename.startswith("000") or filename.startswith("025"):
            # KEEP 000 and 025
            continue
        if not filename.endswith(".py"):
            continue
            
        print(f"Blanking {filename}...")
        filepath = os.path.join(VERSIONS_DIR, filename)
        with open(filepath, "r") as f:
            content = f.read()
            
        # Regex replace upgrade body
        # def upgrade() -> None: ...
        # to def upgrade() -> None: pass
        
        pattern_up = r"def upgrade\(\)( -> None)?:\n(    .*(\n|$))+"
        content = re.sub(r"(def upgrade.*?:).*?(?=\ndef downgrade)", r"\1\n    pass\n", content, flags=re.DOTALL)
        
        # Downgrade
        content = re.sub(r"(def downgrade.*?:).*?$", r"\1\n    pass\n", content, flags=re.DOTALL)
        
        with open(filepath, "w") as f:
            f.write(content)

if __name__ == "__main__":
    baseline_id = fix_000()
    fix_001(baseline_id)
    blank_out_intermediate()

