"""baseline_000

Revision ID: bd61460961e0
Revises: 
Create Date: 2025-12-18 22:06:48.264933

"""
from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd61460961e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_templates_is_active'), 'chart_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_chart_templates_jurisdiction'), 'chart_templates', ['jurisdiction'], unique=False)
    op.create_table('coa_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coa_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ucid', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('inactivated_at', sa.DateTime(), nullable=True),
    sa.Column('inactivated_by', sa.String(), nullable=True),
    sa.Column('subscription_type', sa.Enum('NATIVE', 'STRIPE', name='subscriptiontype'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trade_name', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('onboarding_status', sa.Enum('DRAFT', 'TEMPLATE_SELECTED', 'CHART_READY', 'CHART_FINALIZED', 'ACTIVE', name='onboardingstatus'), nullable=False),
    sa.Column('onboarding_current_step', sa.Integer(), nullable=False),
    sa.Column('onboarding_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_session_lock', sa.UUID(), nullable=True),
    sa.Column('onboarding_session_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index('ix_companies_name_active', 'companies', ['name'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_companies_onboarding_status'), 'companies', ['onboarding_status'], unique=False)
    op.create_index(op.f('ix_companies_ucid'), 'companies', ['ucid'], unique=True)
    op.create_index('ix_companies_ucid_active', 'companies', ['ucid'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('master_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=1), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('normal_balance', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('parent_code', sa.String(), nullable=True),
    sa.Column('fs_mapping', sa.String(), nullable=True),
    sa.Column('cash_flow_classification', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('default_vendors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('regulatory_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_center', sa.String(), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['master_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_accounts_code'), 'master_accounts', ['code'], unique=True)
    op.create_index(op.f('ix_master_accounts_parent_id'), 'master_accounts', ['parent_id'], unique=False)
    op.create_table('organizer_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('normalized_text', sa.String(), nullable=False),
    sa.Column('chosen_category', sa.String(), nullable=False),
    sa.Column('chosen_parent', sa.String(), nullable=True),
    sa.Column('chosen_type', sa.String(), nullable=True),
    sa.Column('chosen_nature', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizer_memory_normalized_text'), 'organizer_memory', ['normalized_text'], unique=False)
    op.create_table('organizer_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_pattern', sa.String(), nullable=False),
    sa.Column('suggested_category', sa.String(), nullable=False),
    sa.Column('suggested_parent', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizer_rules_rule_pattern'), 'organizer_rules', ['rule_pattern'], unique=True)
    op.create_table('pending_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('stripe_session_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_registrations_email'), 'pending_registrations', ['email'], unique=False)
    op.create_index(op.f('ix_pending_registrations_stripe_session_id'), 'pending_registrations', ['stripe_session_id'], unique=False)
    op.create_index(op.f('ix_pending_registrations_token'), 'pending_registrations', ['token'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('allow_public_signup', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('preferred_company_id', sa.UUID(), nullable=True),
    sa.Column('force_password_reset', sa.Boolean(), nullable=False),
    sa.Column('password_reset_required_at', sa.DateTime(), nullable=True),
    sa.Column('last_password_change', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_uid'), 'users', ['user_uid'], unique=True)
    op.create_table('chart_template_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('master_account_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('allow_custom_children', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_account_id'], ['master_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['chart_template_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['chart_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_template_accounts_master_account_id'), 'chart_template_accounts', ['master_account_id'], unique=False)
    op.create_index(op.f('ix_chart_template_accounts_parent_id'), 'chart_template_accounts', ['parent_id'], unique=False)
    op.create_index(op.f('ix_chart_template_accounts_template_id'), 'chart_template_accounts', ['template_id'], unique=False)
    op.create_table('company_template_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['chart_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_template_usage_company_id'), 'company_template_usage', ['company_id'], unique=True)
    op.create_index(op.f('ix_company_template_usage_template_id'), 'company_template_usage', ['template_id'], unique=False)
    op.create_table('elevation_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('requested_role', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiscal_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.Enum('MONTH', 'QUARTER', 'YEAR', name='periodtype'), nullable=False),
    sa.Column('period_number', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'LOCKED', name='periodstatus'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiscal_periods_company_id'), 'fiscal_periods', ['company_id'], unique=False)
    op.create_table('group_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('oauth_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='OAuth provider name (google, microsoft, apple)'),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False, comment="Stable user ID from provider (e.g., Google 'sub' claim)"),
    sa.Column('email_at_provider', sa.String(length=255), nullable=False, comment='Email address as registered with provider'),
    sa.Column('email_verified', sa.Boolean(), nullable=False, comment='Whether provider has verified this email'),
    sa.Column('access_token', sa.Text(), nullable=True, comment='OAuth access token from provider (for future API calls, not active refresh)'),
    sa.Column('refresh_token', sa.Text(), nullable=True, comment='OAuth refresh token from provider (for future token rotation, not active)'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='When the access token expires (tracked but not enforced yet)'),
    sa.Column('raw_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full ID token claims from provider (sanitized)'),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True, comment="User's profile picture from provider"),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='Last successful OAuth login via this provider'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_accounts_provider'), 'oauth_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_index('ix_oauth_user_provider', 'oauth_accounts', ['user_id', 'provider'], unique=False)
    op.create_index('uq_oauth_provider_account', 'oauth_accounts', ['provider', 'provider_account_id'], unique=True)
    op.create_table('qbo_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('realm_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qbo_tokens_company_id'), 'qbo_tokens', ['company_id'], unique=True)
    op.create_index(op.f('ix_qbo_tokens_realm_id'), 'qbo_tokens', ['realm_id'], unique=False)
    op.create_table('user_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('mapped_master_account_id', sa.UUID(), nullable=True),
    sa.Column('template_account_id', sa.UUID(), nullable=True),
    sa.Column('locked_by', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=1), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype'), nullable=True),
    sa.Column('normal_balance', sa.Enum('DEBIT', 'CREDIT', name='normalbalance'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_reason', sa.Enum('FIRST_TRANSACTION', 'PERIOD_CLOSE', 'MANUAL', name='lockedreason'), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('json_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mapped_master_account_id'], ['master_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['company_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_account_id'], ['chart_template_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_accounts_code'), 'company_accounts', ['code'], unique=False)
    op.create_index(op.f('ix_company_accounts_company_id'), 'company_accounts', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_accounts_mapped_master_account_id'), 'company_accounts', ['mapped_master_account_id'], unique=False)
    op.create_index(op.f('ix_company_accounts_parent_id'), 'company_accounts', ['parent_id'], unique=False)
    op.create_index(op.f('ix_company_accounts_template_account_id'), 'company_accounts', ['template_account_id'], unique=False)
    op.create_table('group_company_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_company_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['group_company_id'], ['group_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_company_id', 'company_id', name='uq_group_company_member')
    )
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email of person being invited (case-insensitive match)'),
    sa.Column('target_type', sa.String(length=20), nullable=False, comment="Type of invitation: 'company' (v1 only) or 'group' (future)"),
    sa.Column('company_id', sa.UUID(), nullable=True, comment='Company ID for company invitations'),
    sa.Column('group_id', sa.UUID(), nullable=True, comment='Group ID for group invitations (not yet implemented)'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Role: admin, member, viewer, etc.'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Whether invitee will be admin (for companies)'),
    sa.Column('can_edit', sa.Boolean(), nullable=False, comment='Whether invitee can edit (for companies)'),
    sa.Column('can_view', sa.Boolean(), nullable=False, comment='Whether invitee can view (for companies)'),
    sa.Column('inviter_id', sa.UUID(), nullable=True, comment='User who created the invitation'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: pending, accepted, declined, expired'),
    sa.Column('accepted_at', sa.DateTime(), nullable=True, comment='When invitation was accepted'),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True, comment='User who accepted the invitation'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='When invitation expires'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['group_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index('ix_invitations_email_status', 'invitations', ['email', 'status'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_period_id', sa.UUID(), nullable=False),
    sa.Column('entry_number', sa.String(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('entry_type', sa.Enum('STANDARD', 'ADJUSTING', 'CLOSING', 'REVERSING', 'OPENING', name='entrytype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'VOID', name='entrystatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('posted_by', sa.UUID(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('reverses_entry_id', sa.UUID(), nullable=True),
    sa.Column('reversed_by_entry_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['fiscal_periods.id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reversed_by_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['reverses_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_company_id'), 'journal_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], unique=False)
    op.create_index(op.f('ix_journal_entries_fiscal_period_id'), 'journal_entries', ['fiscal_period_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_status'), 'journal_entries', ['status'], unique=False)
    op.create_table('account_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('company_account_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_period_id', sa.UUID(), nullable=False),
    sa.Column('beginning_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_debits', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_credits', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ending_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_account_id'], ['company_accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['fiscal_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_account_id', 'fiscal_period_id', name='uq_account_period')
    )
    op.create_index(op.f('ix_account_balances_company_account_id'), 'account_balances', ['company_account_id'], unique=False)
    op.create_index(op.f('ix_account_balances_company_id'), 'account_balances', ['company_id'], unique=False)
    op.create_index(op.f('ix_account_balances_fiscal_period_id'), 'account_balances', ['fiscal_period_id'], unique=False)
    op.create_table('account_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_account_id', sa.UUID(), nullable=False),
    sa.Column('master_code', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('propagated_from', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_account_id'], ['company_accounts.id'], ),
    sa.ForeignKeyConstraint(['propagated_from'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_mappings_master_code'), 'account_mappings', ['master_code'], unique=False)
    op.create_index(op.f('ix_account_mappings_status'), 'account_mappings', ['status'], unique=False)
    op.create_table('journal_entry_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('company_account_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_account_id'], ['company_accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_lines_company_account_id'), 'journal_entry_lines', ['company_account_id'], unique=False)
    op.create_index(op.f('ix_journal_entry_lines_journal_entry_id'), 'journal_entry_lines', ['journal_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entry_lines_journal_entry_id'), table_name='journal_entry_lines')
    op.drop_index(op.f('ix_journal_entry_lines_company_account_id'), table_name='journal_entry_lines')
    op.drop_table('journal_entry_lines')
    op.drop_index(op.f('ix_account_mappings_status'), table_name='account_mappings')
    op.drop_index(op.f('ix_account_mappings_master_code'), table_name='account_mappings')
    op.drop_table('account_mappings')
    op.drop_index(op.f('ix_account_balances_fiscal_period_id'), table_name='account_balances')
    op.drop_index(op.f('ix_account_balances_company_id'), table_name='account_balances')
    op.drop_index(op.f('ix_account_balances_company_account_id'), table_name='account_balances')
    op.drop_table('account_balances')
    op.drop_index(op.f('ix_journal_entries_status'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_fiscal_period_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_number'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_company_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index('ix_invitations_email_status', table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_table('group_company_members')
    op.drop_index(op.f('ix_company_accounts_template_account_id'), table_name='company_accounts')
    op.drop_index(op.f('ix_company_accounts_parent_id'), table_name='company_accounts')
    op.drop_index(op.f('ix_company_accounts_mapped_master_account_id'), table_name='company_accounts')
    op.drop_index(op.f('ix_company_accounts_company_id'), table_name='company_accounts')
    op.drop_index(op.f('ix_company_accounts_code'), table_name='company_accounts')
    op.drop_table('company_accounts')
    op.drop_table('user_companies')
    op.drop_index(op.f('ix_qbo_tokens_realm_id'), table_name='qbo_tokens')
    op.drop_index(op.f('ix_qbo_tokens_company_id'), table_name='qbo_tokens')
    op.drop_table('qbo_tokens')
    op.drop_index('uq_oauth_provider_account', table_name='oauth_accounts')
    op.drop_index('ix_oauth_user_provider', table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_provider'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_table('group_companies')
    op.drop_index(op.f('ix_fiscal_periods_company_id'), table_name='fiscal_periods')
    op.drop_table('fiscal_periods')
    op.drop_table('elevation_requests')
    op.drop_index(op.f('ix_company_template_usage_template_id'), table_name='company_template_usage')
    op.drop_index(op.f('ix_company_template_usage_company_id'), table_name='company_template_usage')
    op.drop_table('company_template_usage')
    op.drop_index(op.f('ix_chart_template_accounts_template_id'), table_name='chart_template_accounts')
    op.drop_index(op.f('ix_chart_template_accounts_parent_id'), table_name='chart_template_accounts')
    op.drop_index(op.f('ix_chart_template_accounts_master_account_id'), table_name='chart_template_accounts')
    op.drop_table('chart_template_accounts')
    op.drop_index(op.f('ix_users_user_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_pending_registrations_token'), table_name='pending_registrations')
    op.drop_index(op.f('ix_pending_registrations_stripe_session_id'), table_name='pending_registrations')
    op.drop_index(op.f('ix_pending_registrations_email'), table_name='pending_registrations')
    op.drop_table('pending_registrations')
    op.drop_index(op.f('ix_organizer_rules_rule_pattern'), table_name='organizer_rules')
    op.drop_table('organizer_rules')
    op.drop_index(op.f('ix_organizer_memory_normalized_text'), table_name='organizer_memory')
    op.drop_table('organizer_memory')
    op.drop_index(op.f('ix_master_accounts_parent_id'), table_name='master_accounts')
    op.drop_index(op.f('ix_master_accounts_code'), table_name='master_accounts')
    op.drop_table('master_accounts')
    op.drop_index('ix_companies_ucid_active', table_name='companies', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_companies_ucid'), table_name='companies')
    op.drop_index(op.f('ix_companies_onboarding_status'), table_name='companies')
    op.drop_index('ix_companies_name_active', table_name='companies', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('coa_templates')
    op.drop_table('coa_snapshots')
    op.drop_index(op.f('ix_chart_templates_jurisdiction'), table_name='chart_templates')
    op.drop_index(op.f('ix_chart_templates_is_active'), table_name='chart_templates')
    op.drop_table('chart_templates')
    # ### end Alembic commands ###