"""add_module_type_and_required_module

Revision ID: 51cf6bcdf646
Revises: 025
Create Date: 2025-12-20 21:35:37.677049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51cf6bcdf646'
down_revision = '025'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create moduletype enum
    module_type = sa.Enum('ACCOUNTING', 'FISCAL', 'INVOICING', 'CONTRACTS', 'INVENTORY', 'PAYROLL', name='moduletype')
    module_type.create(op.get_bind(), checkfirst=True)
    
    op.add_column('chart_template_accounts', sa.Column('required_module', sa.Enum('ACCOUNTING', 'FISCAL', 'INVOICING', 'CONTRACTS', 'INVENTORY', 'PAYROLL', name='moduletype'), nullable=True))
    op.add_column('companies', sa.Column('legal_nature', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('economic_activity', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('is_standalone', sa.Boolean(), nullable=False))
    op.drop_constraint('entity_tax_profiles_company_id_key', 'entity_tax_profiles', type_='unique')
    op.drop_index('ix_entity_tax_profiles_company_id', table_name='entity_tax_profiles')
    op.create_index(op.f('ix_entity_tax_profiles_company_id'), 'entity_tax_profiles', ['company_id'], unique=True)
    op.drop_constraint('entity_tax_profiles_company_id_fkey', 'entity_tax_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'entity_tax_profiles', 'companies', ['company_id'], ['id'])
    op.drop_constraint('tax_adjustments_company_id_fkey', 'tax_adjustments', type_='foreignkey')
    op.create_foreign_key(None, 'tax_adjustments', 'companies', ['company_id'], ['id'])
    op.drop_constraint('tax_facts_account_id_fkey', 'tax_facts', type_='foreignkey')
    op.drop_constraint('tax_facts_company_id_fkey', 'tax_facts', type_='foreignkey')
    op.create_foreign_key(None, 'tax_facts', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'tax_facts', 'company_accounts', ['account_id'], ['id'])
    op.create_index(op.f('ix_tax_positions_company_id'), 'tax_positions', ['company_id'], unique=False)
    op.drop_constraint('tax_positions_company_id_fkey', 'tax_positions', type_='foreignkey')
    op.create_foreign_key(None, 'tax_positions', 'companies', ['company_id'], ['id'])
    op.drop_constraint('tax_runs_ruleset_id_fkey', 'tax_runs', type_='foreignkey')
    op.drop_constraint('tax_runs_company_id_fkey', 'tax_runs', type_='foreignkey')
    op.create_foreign_key(None, 'tax_runs', 'tax_rulesets', ['ruleset_id'], ['id'])
    op.create_foreign_key(None, 'tax_runs', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tax_runs', type_='foreignkey')
    op.drop_constraint(None, 'tax_runs', type_='foreignkey')
    op.create_foreign_key('tax_runs_company_id_fkey', 'tax_runs', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tax_runs_ruleset_id_fkey', 'tax_runs', 'tax_rulesets', ['ruleset_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'tax_positions', type_='foreignkey')
    op.create_foreign_key('tax_positions_company_id_fkey', 'tax_positions', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tax_positions_company_id'), table_name='tax_positions')
    op.drop_constraint(None, 'tax_facts', type_='foreignkey')
    op.drop_constraint(None, 'tax_facts', type_='foreignkey')
    op.create_foreign_key('tax_facts_company_id_fkey', 'tax_facts', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tax_facts_account_id_fkey', 'tax_facts', 'company_accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'tax_adjustments', type_='foreignkey')
    op.create_foreign_key('tax_adjustments_company_id_fkey', 'tax_adjustments', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'entity_tax_profiles', type_='foreignkey')
    op.create_foreign_key('entity_tax_profiles_company_id_fkey', 'entity_tax_profiles', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_entity_tax_profiles_company_id'), table_name='entity_tax_profiles')
    op.create_index('ix_entity_tax_profiles_company_id', 'entity_tax_profiles', ['company_id'], unique=False)
    op.create_unique_constraint('entity_tax_profiles_company_id_key', 'entity_tax_profiles', ['company_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('companies', 'is_standalone')
    op.drop_column('companies', 'economic_activity')
    op.drop_column('companies', 'legal_nature')
    op.drop_column('chart_template_accounts', 'required_module')
    
    # Drop enum type
    module_type = sa.Enum('ACCOUNTING', 'FISCAL', 'INVOICING', 'CONTRACTS', 'INVENTORY', 'PAYROLL', name='moduletype')
    module_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
