"""
Integration Job Schemas.

PHASE 1.5: Operational Extraction - Python Integration

Pydantic schemas for triggering jobs in Go worker and receiving callbacks.

CANONICAL REFERENCE:
- docs/canonical/API_CONTRACTS.md (Section 5: Python ↔ Go)
- Pattern A: Python triggers job (POST /jobs to Go)
- Pattern B: Go calls back with results (POST /callback to Python)
"""
from typing import Dict, Any, List, Optional
from uuid import UUID
from pydantic import BaseModel, Field
from datetime import datetime


# ============================================================================
# Pattern A: Python → Go (Job Trigger)
# ============================================================================

class JobCallbackConfig(BaseModel):
    """Callback configuration for Go worker."""
    url: str = Field(..., description="Python callback URL")
    auth: str = Field(default="internal", description="Auth type (internal for now)")


class JobTriggerRequest(BaseModel):
    """
    Request to trigger a job in Go worker.
    Sent from Python → Go.
    """
    job_type: str = Field(..., description="Job type (e.g., 'qbo.sync_accounts')")
    company_id: UUID = Field(..., description="Target company UUID")
    payload: Dict[str, Any] = Field(..., description="Job-specific payload")
    callback: JobCallbackConfig = Field(..., description="Callback configuration")

    class Config:
        json_schema_extra = {
            "example": {
                "job_type": "qbo.sync_accounts",
                "company_id": "550e8400-e29b-41d4-a716-446655440000",
                "payload": {
                    "realm_id": "1234567890",
                    "access_token": "bearer-token",
                    "full_sync": False
                },
                "callback": {
                    "url": "http://localhost:8000/api/v1/integrations/jobs/callback",
                    "auth": "internal"
                }
            }
        }


class JobTriggerResponse(BaseModel):
    """
    Response from Go worker after job submission.
    """
    job_id: UUID = Field(..., description="Generated job ID from Go")
    status: str = Field(..., description="Job status ('accepted')")

    class Config:
        json_schema_extra = {
            "example": {
                "job_id": "ccd56520-4e86-4676-96c4-e5b52b2e2701",
                "status": "accepted"
            }
        }


# ============================================================================
# Pattern B: Go → Python (Callback)
# ============================================================================

class JobError(BaseModel):
    """Error detail from job execution."""
    code: str = Field(..., description="Error code (AEQ_*)")
    message: str = Field(..., description="Human-readable error message")


class QBOAccountRaw(BaseModel):
    """Raw QuickBooks account as received from Go worker."""
    id: str = Field(..., description="QuickBooks account ID")
    name: str = Field(..., description="Account name")
    type: str = Field(..., description="QuickBooks account type")
    subtype: Optional[str] = Field(None, description="QuickBooks account subtype")
    active: bool = Field(..., description="Active status")
    currency: str = Field(..., description="Currency code")
    source: str = Field(default="quickbooks", description="Always 'quickbooks'")


class QBOSyncResult(BaseModel):
    """Result payload for qbo.sync_accounts job."""
    accounts: List[QBOAccountRaw] = Field(..., description="List of raw QBO accounts")
    source: str = Field(..., description="Source identifier")
    count: int = Field(..., description="Number of accounts")


class JobCallbackPayload(BaseModel):
    """
    Callback payload from Go worker to Python.
    Sent from Go → Python.

    CRITICAL:
    - This is the authoritative contract for callbacks
    - Must match API_CONTRACTS.md exactly
    - Python validates this schema before processing
    """
    job_id: UUID = Field(..., description="Job ID generated by Go")
    job_type: str = Field(..., description="Job type that was executed")
    company_id: UUID = Field(..., description="Target company")
    status: str = Field(..., description="Job status: 'succeeded' or 'failed'")
    result: Optional[Dict[str, Any]] = Field(None, description="Job result (null if failed)")
    errors: List[JobError] = Field(default_factory=list, description="List of errors (if failed)")

    class Config:
        json_schema_extra = {
            "example": {
                "job_id": "ccd56520-4e86-4676-96c4-e5b52b2e2701",
                "job_type": "qbo.sync_accounts",
                "company_id": "550e8400-e29b-41d4-a716-446655440000",
                "status": "succeeded",
                "result": {
                    "accounts": [
                        {
                            "id": "1",
                            "name": "Cash",
                            "type": "Bank",
                            "subtype": "CashOnHand",
                            "active": True,
                            "currency": "USD",
                            "source": "quickbooks"
                        }
                    ],
                    "source": "quickbooks",
                    "count": 1
                },
                "errors": []
            }
        }


class JobCallbackResponse(BaseModel):
    """Response sent back to Go worker after processing callback."""
    status: str = Field(..., description="Processing status")
    message: str = Field(..., description="Human-readable message")
    records_staged: Optional[int] = Field(None, description="Number of records staged")

    class Config:
        json_schema_extra = {
            "example": {
                "status": "accepted",
                "message": "Staged 245 accounts",
                "records_staged": 245
            }
        }


# ============================================================================
# Internal Python Schemas
# ============================================================================

class StagingQBOAccountCreate(BaseModel):
    """Internal schema for creating staging records."""
    job_id: UUID
    request_id: UUID
    correlation_id: UUID
    company_id: UUID
    source_account_id: str
    name: str
    account_type: Optional[str]
    account_subtype: Optional[str]
    active: bool
    currency: Optional[str]
    raw_payload: Dict[str, Any]
